name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          RESET_PASS_BASE_URL: ${{ secrets.RESET_PASS_BASE_URL }}
          CONFIRMATION_EMAIL_BASE_URL: ${{ secrets.CONFIRMATION_EMAIL_BASE_URL }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          AWS_ACC_KEY_ID: ${{ secrets.AWS_ACC_KEY_ID }}
          AWS_SECRET_ACC_KEY: ${{ secrets.AWS_SECRET_ACC_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          MAIL_SMTP_AUTH: ${{secrets.MAIL_SMTP_AUTH}}
          MAIL_SMTP_SSL_ENABLE: ${{secrets.MAIL_SMTP_SSL_ENABLE}}
